name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: "14"  

      - name: Install and Build 🔧
        # argument parsing for npm run build
        # TODO: Use repository name per default?
        run: |
          npm install
          npm run build -- --pathprefix=11ty-plain-bootstrap5

      - name: Deploy to Github Pages 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          branch: gh-pages
          folder: _site #the static site

      # If you need more privacy / no tracking,
      # sync your site to your own webspace
      # https://github.com/marketplace/actions/ftp-deploy
      #- name: 📂 Sync files
      #  uses: SamKirkland/FTP-Deploy-Action@4.1.0
      #  with:
      #    server: ftp.samkirkland.com
      #    username: myFtpUserName
      #    password: ${{ secrets.ftp_password }}